name: Basic CI Workflow

# Trigger the workflow on push events to the main branch
on: 
  push:
    branches:
      - main

# Define a single job for this workflow
jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a simple script
      run: echo "Hello, GitHub Actions!"
